### ISSUE TITLE
World configuration

### ISSUE THREAD

**Issue by Annilius** [YellowPhoenix18/RealisticWorldGenerator#19]
Hello i created a world with Multiverse and the right parameter to use Realistic World Generator, then i modified the world's generator config, but what must i do now ? For exemple i modified the "generate-village: true" to false in the world's generator file, and i did /mv regen [world name] (worked) but villages are still here in the world. I think it's not what i should do, can you help me ?

**Comment by Annilius** [comment]
and there is still dungeons evenf if i disabled them before (i tried to stop -> run the server, nothing had changed)

**Comment by YellowPhoenix18** [comment]
Hello, first of all: This is an Issue-Report-System, this is not for private questions and personal problems. In case of personal problems we suggest you to use the SpigotPM-Function, because we get notifications there.

The addition of an additional parameter does not affect the RWG-Config. Please read the Dokumentation of RWG at https://wiki.yellowphoenix18.de !

In RWG it is also currently not possible to disable Villages, but you can disable dungeons by removing them from the shematics-section of the specific biome in the biomes.yml.
